### ISSUE TITLE
Falta un miembro del equipo

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twA109-guillermo-noelia#1]
Falta Noelia por unirse. Se debe unir via moodel en el apartado Trabajo de Equipo para que los profesores puedan verla en este repositorio y puedan calificarla.

**Comment by guillermomlechuga** [comment]
A Noelia no le deja añadirse al grupo, llevamos varios días intentándolo, y no le deja

**Comment by MPerezMateo** [comment]
Estáis ya todos, voy a cerrar la issue
