### ISSUE TITLE
Quitar números de matrícula 

### ISSUE THREAD

**Issue by Juliauru** [aigora/twA109-guillermo-noelia#2]
Hola, 
Os recuerdo que sigue faltando que Noelia se meta en el equipo. Además, no debéis poner vuesto número de matrícula sino vuestro usuario de GitHub. Toda la información la encontraréis en la Wiki del repositiorio [Punto_Inicio](https://github.com/aigora/punto_inicio)

**Comment by Juliauru** [comment]
Por favor, quitad vuestro número de matrícula, y se termina el plazo para entrar al grupo. Si no lo hace tu compañero no podrá ser evaluado.

**Comment by MPerezMateo** [comment]
Ya los han quitado, voy a cerrarles esta issue
